### ISSUE TITLE
Slå sammen til bare en styles.css fil

### ISSUE THREAD

**Issue by Bekkalizer** [Praksiselever-Abaris/SwissArmyKnife#10]
Det er best å ha færre styles css filer. Prøv å slå sammen så alle sidene bruker den samme filen.

**Comment by KingZesty** [comment]
Kan være lurt å ha en på hver side slik at du kan justere på hver enkelt side.

**Comment by Bekkalizer** [comment]
Det er best å ha en sentral masterfil, og så heller overstyre på hver enkelt side dersom det er noe som skal være annerledes. Slå dem sammen for now, så kan jeg vise deg hvordan vi overstyrer når det blir aktuelt.
