### ISSUE TITLE
Områdekart

### ISSUE THREAD

**Issue by Bekkalizer** [Praksiselever-Abaris/SwissArmyKnife#16]
Utforsk muligheter for markering av områder i kartmodulen. Gjør dette i en egen branch som heter map-explore

**Comment by Bekkalizer** [comment]
Sjekk dette: https://fusiontables.google.com/DataSource?dsrcid=1372985
Klikk på "geometry" @KingZesty @Raxzz

**Comment by Raxzz** [comment]
options = $.extend({
    scrollwheel: false,
    navigationControl: false,
    mapTypeControl: false,
    scaleControl: false,
    draggable: false,
    mapTypeId: google.maps.MapTypeId.ROADMAP
}, options);
